apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-api-27981
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/core-api-27981
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
